M48
; DRILL file {KiCad 9.0.2+dfsg-1} date 2026-03-20T18:51:26-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-20T18:51:26-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C9.000
%
G90
G05
T1
X269.0Y-8.0
T2
X108.7Y-72.5
X172.7Y-72.5
M30
